# Assignment: Data Wrangling

### Reading material: `tidy_data.pdf`

**Q1.** This question provides some practice cleaning variables which have common problems.
1. For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)
2. For the Minnesota police use of for data, `./data/mn_police_use_of_force.csv`, clean the `subject_injury` variable, handling the NA's; this gives a value `Yes` when a person was injured by police, and `No` when no injury occurred. What proportion of the values are missing? Is this a concern? Cross-tabulate your cleaned `subject_injury` variable with the `force_type` variable. Are there any patterns regarding when the data are missing?

**Q2.** Go to https://sharkattackfile.net/ and download their dataset on shark attacks (Hint: `GSAF5.xls`).

1. Open the shark attack file using Pandas. It is probably not a csv file, so `read_csv` won't work.
2. Drop any columns that do not contain data.
3. Clean the year variable. Describe the range of values you see. Filter the rows to focus on attacks since 1940. Are attacks increasing, decreasing, or remaining constant over time?
4. Clean the Age variable and make a histogram of the ages of the victims.
5. What proportion of victims are male?
6. Clean the `Type` variable so it only takes three values: Provoked and Unprovoked and Unknown. What proportion of attacks are unprovoked?

---

## *Phase 1: Solution without AI

Complete all questions in the following cells without generative AI. Then commit and push the
notebook before beginning Phase 2.

**Declaration:** I completed this version without generative AI.

**Student(s):** I completed this version without generative AI

**Date:** 09/02/2026

**QUESTION 1A**

In [3]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [17]:
# Your Phase 1 solution to the problem goes here.

import pandas as pd

df_air = pd.read_csv("airbnb_hw.csv")
df_air.head(10)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
5,1039,7/25/2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0
6,1783,8/12/2008,Amazing Also,Manhattan,Apartment,100.0,Entire home/apt,10004.0,1.0,1,9,250,100.0
7,2078,8/15/2008,"Colorful, quiet, & near the subway!",Brooklyn,Apartment,90.0,Private room,11201.0,1.0,1,80,90,94.0
8,2339,8/20/2008,East Village Cocoon: 2 Bedroom Flat,Manhattan,Apartment,90.0,Entire home/apt,10009.0,2.0,1,95,270,90.0
9,2339,8/20/2008,Lovely 2 Bedroom East Village Nest,Manhattan,Apartment,95.0,Entire home/apt,10009.0,2.0,1,23,290,96.0

In [18]:
df_air.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30478 entries, 0 to 30477
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Host Id                     30478 non-null  int64
 1   Host Since                  30475 non-null  object
 2   Name                        30478 non-null  object
 3   Neighbourhood               30478 non-null  object
 4   Property Type               30475 non-null  object
 5   Review Scores Rating (bin)  22155 non-null  float64
 6   Room Type                   30478 non-null  object
 7   Zipcode                     30344 non-null  float64
 8   Beds                        30393 non-null  float64
 9   Number of Records           30478 non-null  int64
 10  Number Of Reviews           30478 non-null  int64
 11  Price                       30478 non-null  object
 12  Review Scores Rating        22155 non-null  float64
dtypes: float64(4), int64(3), object(6)
memory usage: 3.0+ MB

In [20]:
df_air['Price'] = df_air['Price'].astype(str).str.replace(',', '', regex=False)
df_air['Price'] = df_air['Price'].astype(str).str.replace('$', '', regex=False)
df_air['Price'] = pd.to_numeric(df_air['Price'], errors='coerce')

n_missing_price = df_air['Price'].isnull().sum()
print(n_missing_price)

0

1) Cleaning Decisions

When values in the price column exceed three digits, formatting adds commas, which would cause Pandas to read price as an object, specifically a string, instead of a numeric value. The same effect would happen if there are any currency indicators before the actual price value, so I chose to strip both commas and dollar symbols from the column.

Since the price column is defined as a string, it should also be converted to a numeric variable so that any missing values will show up as NaN and not impact data analysis/visualization in the future.

2) Number of Missing Values

After cleaning, I'm left with 0 missing values in the price column

**QUESTION 1B**

In [15]:
import pandas as pd

df_pol = pd.read_csv("mn_police_use_of_force.csv")
df_pol.head()

,response_datetime,problem,is_911_call,primary_offense,subject_injury,force_type,force_type_action,race,sex,age,type_resistance,precinct,neighborhood
0,2016/01/01 00:47:36,Assault in Progress,Yes,DASLT1,NaN,Bodily Force,Body Weight to Pin,Black,Male,20.0,Tensed,1,Downtown East
1,2016/01/01 02:19:34,Fight,No,DISCON,NaN,Chemical Irritant,Personal Mace,Black,Female,27.0,Verbal Non-Compliance,1,Downtown West
2,2016/01/01 02:19:34,Fight,No,DISCON,NaN,Chemical Irritant,Personal Mace,White,Female,23.0,Verbal Non-Compliance,1,Downtown West
3,2016/01/01 02:28:48,Fight,No,PRIORI,NaN,Chemical Irritant,Crowd Control Mace,Black,Male,20.0,Commission of Crime,1,Downtown West
4,2016/01/01 02:28:48,Fight,No,PRIORI,NaN,Chemical Irritant,Crowd Control Mace,Black,Male,20.0,Commission of Crime,1,Downtown West

In [28]:
# checking subject_injury data to get Yes/No/NaN counts
print(df_pol["subject_injury"].value_counts(dropna=False))

subject_injury
NaN    9848
Yes    1631
No     1446
Name: count, dtype: int64

In [43]:
# calculating missing data proportion
prop_missing = (9849/(9848+1631+1446)*100)
print(f"Proportion of missing values:{prop_missing:.4f}")

# replacing any NaN values with No, under the assumption that if an injury status was not documented, it did not happen
df_pol["subject_injury_clean"] = df_pol["subject_injury"].fillna("No")

Proportion of missing values:76.2012

In [44]:
crosstab = pd.crosstab(df_pol['force_type'], df_pol['subject_injury_clean'], )
print(crosstab,"\n")

# new cross-tabulation with the percentage of No to Yes to better understand the data patterns
crosstab_ratio = pd.crosstab(
    df_pol["force_type"],
    df_pol["subject_injury_clean"],
    normalize="index",  # showing ratio missing
) * 100   # converting from decimal to percentage
print(crosstab_ratio.round(4)) # reducing decimal places shown

subject_injury_clean           No   Yes
force_type
Baton                           2     2
Bodily Force                 8144  1286
Chemical Irritant            1552    41
Firearm                         2     0
Gun Point Display              60    44
Improvised Weapon             108    40
Less Lethal                    87     0
Less Lethal Projectile          1     2
Maximal Restraint Technique   170     0
Police K9 Bite                 33    44
Taser                        1135   172

subject_injury_clean               No      Yes
force_type
Baton                         50.0000  50.0000
Bodily Force                  86.3627  13.6373
Chemical Irritant             97.4262   2.5738
Firearm                      100.0000   0.0000
Gun Point Display             57.6923  42.3077
Improvised Weapon             72.9730  27.0270
Less Lethal                  100.0000   0.0000
Less Lethal Projectile        33.3333  66.6667
Maximal Restraint Technique  100.0000   0.0000
Police K9 Bite                42.8571  57.1429
Taser                         86.8401  13.1599

1) Missing Values Proportion

Over 75% of the subject_injury values were missing in the dataset. This proportion could be a concern if officers are deciding to not log injuries when they are a result of extreme/uneccessary physical measures. Such decision could have been made to protect their work status or avoid reprecussions.

However, the missing values proportion could also not be a concern under the assumption that officers simply didn't make a record of subject injury if it didn't occur. This assumption greatly increases the number of "No's".

2) Patterns of Missing Data

I decided to do a second cross tabulation that instead shows the percentage of No/Yes values to more clearly compare the data. Once again with the assumption that unrecorded values indicate a lack of subject injury, we can see that there are higher ratios of missingness for lower-impact and common force tactics like "Less Lethal" and "Bodily Force", as well as for the most extreme force types like "Maximal Restraint Technique" and Chemical Irritant". For the lower-impact types, it could be since officers didn't find the need to log  injuries unless specifically asked it. For the higher-impact injuries, the missingness/no value proportions make sense since officers likely don't have to use extreme tactics very often.

## *Phase 2: AI-assisted Revision
Keep Phase 1 frozen.

- **Phase 1 commit SHA ID:** [To be provided]
- **AI tool and model used:** [To be provided]

### *Prompts used

1. [Paste prompt]
2. [Paste follow-up prompt]

### *AI-proposed changes

[Paste the AI's concise numbered list verbatim.]

1. ...
2. ...

### *Evaluation of AI suggestions

| Change | Decision | Reason and verification |
|---|---|---|
| 1 | Accept / modify / reject | ... |
| 2 | Accept / modify / reject | ... |

### *AI-assisted solution in full
After the evaluation of AI suggestions, incorporate the accepted revisions into your Phase 1 solution and provide the final Phase 2 solution in full in the following cells.

In [ ]:
# Your Phase 2 solution to the problem goes here.

df_air['Price'] = df_air['Price'].astype(str).str.strip()

### *Reflection on AI assistance
In your own words without generative AI.

[In 150–300 words, describe the main improvements, AI mistakes or limitations, how the final solution was verified, and any remaining concerns.]